# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /prova

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the backend files to the container
COPY main.py usuarios.db ./

# Expose the port on which the backend will run
EXPOSE 8000

# Start the backend server
CMD ["python", "main.py"]